### ISSUE TITLE
Gamepad issue

### ISSUE THREAD

**Issue by michaeldai7** [playcanvas/engine#1588]
### Description

[playcanvas-stable.dbg.js:20697]: Cannot read property 'pressed' of undefined

TypeError: Cannot read property 'pressed' of undefined
    at GamePads.isPressed (https://code.playcanvas.com/playcanvas-stable.dbg.js:20697:53)
    at script.Keyboard.update (https://launch.playcanvas.com/api/assets/files/code/hovership/keyboard.js?id=20388985&branchId=fe38dee9-c0ca-4f80-aacb-e4065765d7bc:24:26)
    at ScriptComponent._scriptMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:27235:21)
    at ScriptComponent._onUpdate (https://code.playcanvas.com/playcanvas-stable.dbg.js:27271:14)
    at ScriptComponentSystem._callComponentMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:27653:51)
    at ScriptComponentSystem._onUpdate (https://code.playcanvas.com/playcanvas-stable.dbg.js:27662:10)
    at Function._helper (https://code.playcanvas.com/playcanvas-stable.dbg.js:24352:14)
    at Function.update (https://code.playcanvas.com/playcanvas-stable.dbg.js:24360:10)
    at Application.update (https://code.playcanvas.com/playcanvas-stable.dbg.js:23763:24)
    at https://code.playcanvas.com/playcanvas-stable.dbg.js:24150:11

![image](https://user-images.githubusercontent.com/43862422/59057793-130ea980-8850-11e9-9ba2-fdf3b98ca958.png)

**Comment by willeastcott** [comment]
It's not ```pc.PAD_RINGT```. It's ```pc.PAD_RIGHT```.

**Comment by willeastcott** [comment]
Closing because I'm assuming this is happening because isPressed is being passed undefined for the pad button enum.
