### ISSUE TITLE
Missing property in sample code

### ISSUE THREAD

**Issue by vanderry** [playcanvas/engine#1681]
The samles in question are [WebVR Lab](https://developer.playcanvas.com/en/tutorials/webvr-lab/) and [WebVr Orange Room](https://developer.playcanvas.com/en/tutorials/webvr-orange-room/). Recently, when launching these from the editor, an error message is displayed:

```
[web-vr-ui.js?id=6076849&branchId=2377bd1c-2001-4f78-9f0c-62cc0bee56fb:76]: Cannot read property 'isSupported' of null

TypeError: Cannot read property 'isSupported' of null
    at onEnterVrPressedEvent (https://launch.playcanvas.com/api/assets/files/scripts/web-vr-ui.js?id=6076849&branchId=2377bd1c-2001-4f78-9f0c-62cc0bee56fb:76:33)
    at script.WebVrUi.initialize (https://launch.playcanvas.com/api/assets/files/scripts/web-vr-ui.js?id=6076849&branchId=2377bd1c-2001-4f78-9f0c-62cc0bee56fb:102:9)
    at ScriptComponent._scriptMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:27162:21)
    at ScriptComponent._onInitialize (https://code.playcanvas.com/playcanvas-stable.dbg.js:27180:16)
    at ScriptComponentSystem._callComponentMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:27580:51)
    at ScriptComponentSystem._onInitialize (https://code.playcanvas.com/playcanvas-stable.dbg.js:27585:10)
    at Function._helper (https://code.playcanvas.com/playcanvas-stable.dbg.js:24278:14)
    at Function.initialize (https://code.playcanvas.com/playcanvas-stable.dbg.js:24281:10)
    at Application.start (https://code.playcanvas.com/playcanvas-stable.dbg.js:23704:24)
    at https://launch.playcanvas.com/editor/scene/js/launch.js:7241:25
```

Tested in Chrome, Windows 10, no VR hardware connected.

**Comment by vanderry** [comment]
Moved this to forum in light of guidelines.
