### ISSUE TITLE
Not clear error when trying to use allow listed word for script name

### ISSUE THREAD

**Issue by Sarletor** [playcanvas/engine#3278]
Demo: https://playcanvas.com/editor/scene/1186718

Script:
```
var Data = pc.createScript('data');

Data.prototype.initialize = function() {
    
};

Data.prototype.update = function(dt) {
    
};
```

Error:
```
[playcanvas-stable.dbg.js:63059]: Cannot set property data of # which has only a getter

TypeError: Cannot set property data of # which has only a getter
    at ScriptComponent.create (https://code.playcanvas.com/playcanvas-stable.dbg.js:63059:23)
    at ScriptComponentSystem.initializeComponentData (https://code.playcanvas.com/playcanvas-stable.dbg.js:63396:16)
    at ScriptComponentSystem.addComponent (https://code.playcanvas.com/playcanvas-stable.dbg.js:42890:9)
    at SceneParser._openComponentData (https://code.playcanvas.com/playcanvas-stable.dbg.js:34608:13)
    at SceneParser.parse (https://code.playcanvas.com/playcanvas-stable.dbg.js:34548:9)
    at SceneHandler.open (https://code.playcanvas.com/playcanvas-stable.dbg.js:36550:24)
    at SharedSceneHandler.open (https://launch.playcanvas.com/editor/scene/js/launch.js:11012:34)
    at ResourceLoader.open (https://code.playcanvas.com/playcanvas-stable.dbg.js:36482:19)
    at https://launch.playcanvas.com/editor/scene/js/launch.js:7336:44
    at Application._preloadScripts (https://code.playcanvas.com/playcanvas-stable.dbg.js:69494:5)
```

**Comment by mvaligursky** [comment]
@vkalpias - any thoughts on this one?

**Comment by Maksims** [comment]
This is because scripts are added to ScriptComponent instance, and there are reserved names: https://github.com/playcanvas/engine/blob/master/src/script/script.js#L11
Although it does not lists `data` as reserved, which clashes with `data` getter on Component, as it is inherited by ScriptComponent: https://github.com/playcanvas/engine/blob/master/src/framework/components/component.js#L91

The fix would be to list `data` as a reserved name.
