### ISSUE TITLE
Disabling a model Entity with Clustered lighting gives errors

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4950]
Related thread: https://forum.playcanvas.com/t/solved-cannot-read-properties-of-null-reading-device/29128/

Project: https://playcanvas.com/project/1025290/overview/clustered-lighting-disable-bug

Launch project
Press 1 to disable the cube
Errors appear:

```
Uncaught TypeError: Cannot read properties of null (reading 'width')
    at LightsBuffer.addLightData (lights-buffer.js:400:61)
    at WorldClusters.updateClusters (world-clusters.js:389:31)
    at WorldClusters.update (world-clusters.js:440:14)
    at ForwardRenderer.updateClusters (forward-renderer.js:1913:29)
    at RenderPass.execute (forward-renderer.js:1969:22)
    at RenderPass.render (render-pass.js:215:14)
    at FrameGraph.render (frame-graph.js:127:29)
    at Application.renderComposition (app-base.js:1240:25)
    at Application.render (app-base.js:1228:14)
    at app-base.js:2201:29
```

**Comment by kungfooman** [comment]
![image](https://user-images.githubusercontent.com/5236548/210966580-0b7b83de-2ea1-4b0a-98d2-04bc39355de7.png)

Test project not public?

**Comment by yaustar** [comment]
Made public now
