### ISSUE TITLE
glTF exporter doesn't support Basic materials

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4987]
Project: https://playcanvas.com/project/1029282/overview/glb-export-from-editor

This project changes the capsule material to a Basic Material

Clicking on export glb button will result in an error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'equals')
    at playcanvas-extras.js?id=118242865&branchId=8fa2d08f-2f3d-4fda-ab5e-6f99be4f24fc:2105:23
    at Array.map (<anonymous>)
    at GltfExporter.writeMaterials (playcanvas-extras.js?id=118242865&branchId=8fa2d08f-2f3d-4fda-ab5e-6f99be4f24fc:2091:45)
    at GltfExporter.buildJson (playcanvas-extras.js?id=118242865&branchId=8fa2d08f-2f3d-4fda-ab5e-6f99be4f24fc:2273:11)
    at GltfExporter.build (playcanvas-extras.js?id=118242865&branchId=8fa2d08f-2f3d-4fda-ab5e-6f99be4f24fc:2290:22)
    at ButtonComponent.<anonymous> (export-glb-button.js?id=118405723&branchId=8fa2d08f-2f3d-4fda-ab5e-6f99be4f24fc:23:22)
    at ButtonComponent.fire (event-handler.js:204:26)
    at ButtonComponent._fireIfActive (component.js:352:18)
    at ButtonComponent._onClick (component.js:347:14)
    at ElementComponent.fire (event-handler.js:204:26)
```

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/issues/5001
