### ISSUE TITLE
Exception if one cubemap face texture is Basis compressed

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5226]
Project: https://playcanvas.com/editor/scene/1709149

One or two cubemap faces are Basis compressed and the Editor gives the following error 

```
helpers.ts:111 Uncaught TypeError: Failed to execute 'compressedTexImage2D' on 'WebGL2RenderingContext': parameter 7 is not of type 'ArrayBufferView'.
    at WebglTexture.upload (playcanvas-1.61.3.js:8283:12)
    at WebglGraphicsDevice.setTexture (playcanvas-1.61.3.js:9822:19)
    at WebglGraphicsDevice.draw (playcanvas-1.61.3.js:9914:11)
    at ForwardRenderer.drawInstance (playcanvas-1.61.3.js:21167:12)
    at ForwardRenderer.renderForwardInternal (playcanvas-1.61.3.js:25791:12)
    at ForwardRenderer.renderForward (playcanvas-1.61.3.js:25802:9)
    at ForwardRenderer.renderRenderAction (playcanvas-1.61.3.js:26021:10)
    at ForwardRenderer.renderPassRenderActions (playcanvas-1.61.3.js:25973:10)
    at RenderPass.execute (playcanvas-1.61.3.js:25911:12)
    at RenderPass.render (playcanvas-1.61.3.js:14687:9)
    at FrameGraph.render (playcanvas-1.61.3.js:31504:21)
    at Func.renderComposition (playcanvas-1.61.3.js:34537:20)
    at editor.once.render (viewport-application.js:70:14)
    at viewport-application.js:104:21
```

If I remove the basis compression on those faces, the cubemap renders correctly

**Comment by slimbuck** [comment]
All faces of a cubemap must have the same pixel format since it's actually a single texture. The fix here is to not draco-compress a single face. Perhaps the editor should warn in such a case, but then we need this issue on editor repo.

**Comment by yaustar** [comment]
Should the engine be able to handle this case more gracefully?

**Comment by slimbuck** [comment]
I can imagine this is only an issue in the editor tbh.
