### ISSUE TITLE
TypeError: a.vertexAttribDivisor is not a function

### ISSUE THREAD

**Issue by erikdubbelboer** [playcanvas/engine#6674]
This error is affecting less than 1% of the users of https://poki.com/en/preview/94176748-9ef8-42c9-a44e-a95b70ec5680/da472bf8-04fa-4660-a885-2c2b6b783dda

Affects **only mobile** devices with any version of Chrome up to and including the latest Chrome 125.

I'm afraid the Poki error capturing doesn't capture any more details at the moment. Any specific details that could be useful can be added to this system if you have any suggestions.

This stacktrace is sometimes prefixed with messages like: `Error while loading scene JSON 1329458.json:`
```
TypeError: a.vertexAttribDivisor is not a function
 at t.n.createVertexArray (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:232249)
 at t.n.setBuffers (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:232661)
 at t.n.draw (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:233053)
 at t.drawInstance (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:688631)
 at e.t.submitCasters (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:662170)
 at e.t.renderFace (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:663513)
 at t.i.execute (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:669780)
 at t.render (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:252042)
 at e.t.render (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:862622)
 at i.n.renderComposition (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:911639)
```
If it's useful I could try to put a version of the game live where the source isn't minified.

**Comment by mvaligursky** [comment]
This seems like a case where the instancing is used but not supported on some WebGL 1 device (WebGL2 has it guaranteed).

only use instancing on WebGL if device.extInstancing is true.

I'll close it as it's likely this, but please reopen if not.
