### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'renderTarget')

### ISSUE THREAD

**Issue by erikdubbelboer** [playcanvas/engine#6675]
This error is affecting less than 1% of the users of https://poki.com/en/preview/94176748-9ef8-42c9-a44e-a95b70ec5680/da472bf8-04fa-4660-a885-2c2b6b783dda

Affects both desktop and mobile and any version up to and including the latest Chrome 125.

I'm afraid the Poki error capturing doesn't capture any more details at the moment. Any specific details that could be useful can be added to this system if you have any suggestions.

```
TypeError: Cannot read properties of undefined (reading 'renderTarget')
 at t.setupRenderPass (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:662562)
 at i.update (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:669598)
 at i.update (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:670318)
 at i.buildFrameGraph (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:711334)
 at n.renderComposition (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:911588)
 at n.render (https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:911480)
 at https://94176748-9ef8-42c9-a44e-a95b70ec5680.poki-gdn.com/da472bf8-04fa-4660-a885-2c2b6b783dda/playcanvas-stable.min.js:9:921837
```
If it's useful I could try to put a version of the game live where the source isn't minified.

**Comment by mvaligursky** [comment]
Yes it'd be great to use non-minified / debug engine to capture this in a better form. This perhaps seems to be related to shadow rendering, but not sure. Is this perhaps some WebGL1 related issue? Do you see any devices stats here?
