### ISSUE TITLE
Can't build stable playcanvas engine 0.190.2 on Windows

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#705]
Error while trying to build "**stable**" branch with last commit "**[RELEASE] v0.190.2**".

```
D:\dev\playcanvas-engine\build>node build.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\dev\playcanvas-engine\src\core\core.js
..\src\polyfill\request-animation-frame.js
..\src\polyfill\string.js
..\src\polyfill\fullscreen.js
..\src\core\color.js
..\src\core\guid.js
..\src\core\time.js
..\src\core\uri.js
..\src\core\log.js
..\src\core\inheritance.js
..\src\core\path.js
..\src\core\string.js
..\src\core\debug.js
..\src\core\events.js
..\src\core\tags.js
..\src\core\object-pool.js
..\src\math\math.js
..\src\math\vec2.js
..\src\math\vec3.js
..\src\math\vec4.js
..\src\math\mat3.js
..\src\math\mat4.js
..\src\math\quat.js
..\src\math\curve.js
..\src\math\curve-set.js
..\src\shape\bounding-box.js
..\src\shape\bounding-sphere.js
..\src\shape\frustum.js
..\src\shape\plane.js
..\src\shape\ray.js
..\src\graphics\graphics.js
..\src\graphics\scope-id.js
..\src\graphics\scope-space.js
..\src\graphics\version.js
..\src\graphics\versioned-object.js
..\src\graphics\vertex-iterator.js
..\src\graphics\vertex-format.js
..\src\graphics\vertex-buffer.js
..\src\graphics\index-buffer.js
..\src\graphics\texture.js
..\src\graphics\render-target.js
..\src\graphics\shader-input.js
..\src\graphics\shader.js
..\src\graphics\program-library.js
..\src\graphics\device.js
..\src\graphics\chunks.js
..\src\graphics\simple-post-effect.js
..\src\graphics\prefilter-cubemap.js
..\src\graphics\paraboloid.js
..\src\graphics\program-lib\chunks\generated-shader-chunks.js
..\src\graphics\program-lib\program-lib.js
..\src\graphics\program-lib\basic.js
..\src\graphics\program-lib\depth.js
..\src\graphics\program-lib\depth-rgba.js
..\src\graphics\program-lib\particle.js
..\src\graphics\program-lib\standard.js
..\src\graphics\program-lib\pick.js
..\src\graphics\program-lib\skybox.js
..\src\graphics\post-effect.js
..\src\scene\scene.js
..\src\scene\forward-renderer.js
..\src\scene\graph-node.js
..\src\scene\camera.js
..\src\scene\light.js
..\src\scene\material.js
..\src\scene\basic-material.js
..\src\scene\depth-material.js
..\src\scene\standard-material.js
..\src\scene\mesh.js
..\src\scene\skin.js
..\src\scene\skin-partition.js
..\src\scene\model.js
..\src\scene\particle-emitter.js
..\src\scene\pick.js
..\src\scene\procedural.js
..\src\anim\animation.js
..\src\anim\skeleton.js
..\src\sound\manager.js
..\src\sound\sound.js
..\src\sound\listener.js
..\src\sound\instance.js
..\src\sound\instance3d.js
..\src\audio\channel.js
..\src\audio\channel3d.js
..\src\input\input.js
..\src\input\mouse.js
..\src\input\keyboard.js
..\src\input\game-pads.js
..\src\input\touch.js
..\src\input\controller.js
..\src\net\http.js
..\src\script\script-registry.js
..\src\script\script.js
..\src\framework\script.js
..\src\framework\application.js
..\src\framework\stats.js
..\src\framework\components\registry.js
..\src\framework\components\system.js
..\src\framework\components\component.js
..\src\framework\components\data.js
..\src\framework\components\animation\component.js
..\src\framework\components\animation\system.js
..\src\framework\components\animation\data.js
..\src\framework\components\model\system.js
..\src\framework\components\model\component.js
..\src\framework\components\model\data.js
..\src\framework\components\camera\system.js
..\src\framework\components\camera\component.js
..\src\framework\components\camera\data.js
..\src\framework\components\camera\post-effect-queue.js
..\src\framework\components\light\system.js
..\src\framework\components\light\component.js
..\src\framework\components\light\data.js
..\src\framework\components\script\system.js
..\src\framework\components\script\component.js
..\src\framework\components\script\data.js
..\src\framework\components\script-legacy\system.js
..\src\framework\components\script-legacy\component.js
..\src\framework\components\script-legacy\data.js
..\src\framework\components\sound\constants.js
..\src\framework\components\sound\slot.js
..\src\framework\components\sound\system.js
..\src\framework\components\sound\component.js
..\src\framework\components\sound\data.js
..\src\framework\components\audio-source\system.js
..\src\framework\components\audio-source\component.js
..\src\framework\components\audio-source\data.js
..\src\framework\components\audio-listener\system.js
..\src\framework\components\audio-listener\component.js
..\src\framework\components\audio-listener\data.js
..\src\framework\components\rigid-body\constants.js
..\src\framework\components\rigid-body\system.js
..\src\framework\components\rigid-body\component.js
..\src\framework\components\rigid-body\data.js
..\src\framework\components\collision\trigger.js
..\src\framework\components\collision\system.js
..\src\framework\components\collision\component.js
..\src\framework\components\collision\data.js
..\src\framework\components\particle-system\system.js
..\src\framework\components\particle-system\component.js
..\src\framework\components\particle-system\data.js
..\src\framework\components\text\font.js
..\src\framework\components\text\system.js
..\src\framework\components\text\component.js
..\src\framework\components\text\data.js
..\src\framework\components\zone\system.js
..\src\framework\components\zone\component.js
..\src\framework\components\zone\data.js
..\src\framework\entity.js
..\src\resources\loader.js
..\src\resources\animation.js
..\src\resources\audio.js
..\src\resources\cubemap.js
..\src\resources\json.js
..\src\resources\material.js
..\src\resources\model.js
..\src\resources\script.js
..\src\resources\text.js
..\src\resources\binary.js
..\src\resources\texture.js
..\src\resources\html.js
..\src\resources\css.js
..\src\resources\shader.js
..\src\resources\scene.js
..\src\resources\hierarchy.js
..\src\resources\scene-settings.js
..\src\resources\folder.js
..\src\resources\font.js
..\src\resources\parser\json-model.js
..\src\resources\parser\scene.js
..\src\asset\asset.js
..\src\asset\asset-registry.js
..\src\backwards-compatibility.js
..\src\scene\immediate.js
..\src\scene\lightmapper.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at D:\dev\playcanvas-engine\build\build.js:174:25
    at Array.forEach (native)
    at preprocess (D:\dev\playcanvas-engine\build\build.js:170:18)
    at D:\dev\playcanvas-engine\build\build.js:236:25
    at D:\dev\playcanvas-engine\build\build.js:127:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

I've installed all dependencies including:
- node.js 4.4.7 (x64)
- Java 8 Update 101

**Comment by aidinabedi** [comment]
Found the issue! Please see PR #710
