### ISSUE TITLE
`MultiCamera` events not handled properly

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#7136]
Just tested @willeastcott rope bridge: https://engine-c3vj73m56-playcanvas.vercel.app/#/physics/rope-bridge

Not related to it - but it displays the bug:

```
camera-controls.mjs:668 Uncaught TypeError: Cannot read properties of null (reading 'canvas')
    at CameraControls._look (camera-controls.mjs:668:54)
    at CameraControls._onPointerMove (camera-controls.mjs:540:22)
```

Every time you restart the example, it's collecting never-deleted events (aka destroy/detach isn't called properly).

![image](https://github.com/user-attachments/assets/fc225f97-f851-408c-bb5a-9df16c1ee6cc)

Orbit example displays same issue.

**Comment by kpal81xd** [comment]
I cant repro this can you confirm if its still an issue? @kungfooman

**Comment by kungfooman** [comment]
I just took a Vercel link from 2 hours ago to test: https://engine-o685bw9d0-playcanvas.vercel.app/#/camera/orbit

Definitely still an issue:
1) Refresh a few times
2) Orbit the model

Result:

![image](https://github.com/user-attachments/assets/44a7a23a-b988-4ca5-b6a8-adb9dead0b6d)
